### ISSUE TITLE
Please update to Neo4j 2.1.5

### ISSUE THREAD

**Issue by jexp** [Vinelab/docker-neo4j#1]
perhaps make the version configurable when building the docker image?

**Comment by Mulkave** [comment]
Ah that has been here for a while, sorry. It's 2.1.8 now :smile:

Also the version is held by an environment variable `NEO4J_VERSION` so installing a different version requires replacing the value there only.

Making it available at build-time is proposed so whenever that is there, we get it right away https://github.com/docker/docker/pull/9176
